"""``specsr.__version__`` and the package metadata must not be able to disagree.

They already did: ``__init__.py`` said ``0.1.0.dev0`` while ``pyproject.toml``
said ``0.1.0``, so a user who installed the wheel and printed ``__version__``
got a version that was never released. Two hand-maintained copies of the same
number drift the first time one is bumped alone, and the copy that is wrong is
the one users see -- so the attribute now reads the installed metadata, and this
pins that it keeps doing so.
"""

from __future__ import annotations

import re
from pathlib import Path

import specsr

PYPROJECT = Path(__file__).resolve().parents[1] / "pyproject.toml"


def _declared_version() -> str:
    """The version in pyproject.toml, without needing a TOML parser.

    `tomllib` is standard library only from 3.11, and this package supports
    3.10 -- reaching for it made this module fail to import on the older half
    of the test matrix. The file is generated by nobody and edited by hand, so
    a single anchored line is a fair thing to match.
    """
    match = re.search(r'^version\s*=\s*"([^"]+)"', PYPROJECT.read_text(), re.MULTILINE)
    assert match, "no version = \"...\" line found in pyproject.toml"
    return match.group(1)


def test_version_matches_pyproject():
    declared = _declared_version()
    assert specsr.__version__ == declared, (
        f"specsr.__version__ is {specsr.__version__} but pyproject.toml declares "
        f"{declared}.\n"
        "An editable install records its version at install time, so this also "
        "fires when the version was bumped without reinstalling: try "
        "`pip install -e .` first. If it still disagrees, the version is being "
        "restated somewhere instead of read from the installed metadata."
    )


def test_version_is_not_restated_as_a_literal():
    """A literal assignment is how the two copies drifted the first time."""
    source = (Path(specsr.__file__)).read_text()
    literal = re.search(r'^__version__\s*=\s*["\']', source, re.MULTILINE)
    assert literal is None, (
        "__version__ is assigned a string literal in specsr/__init__.py; derive "
        "it from importlib.metadata instead so it cannot drift from pyproject.toml"
    )
